### ISSUE TITLE
显卡驱动

### ISSUE THREAD

**Issue by smellok** [Lunaleeguo/Surface-Pro-4-Sierra#5]
您好，按照你的说明，装好后，我替换了显卡驱动的kext后（efi也是使用了EFI-USE AFTER INSTALLTION里面的），重启后就出现的花屏。10.12.3版本，I7 16G 256g 版本。

**Comment by Lunaleeguo** [comment]
请问你的Clover版本是多少，我前两天试了下，升级到更高的Clvoer版本后确实会花屏

**Comment by smellok** [comment]
你好，我的clover版本是4047，能不能把可以正确安装，使用的clover版本告诉一下，谢谢！

**Comment by Lunaleeguo** [comment]
直接用EFI-USE AFTER INSTALLTION这里面的Clover版本就可以了

**Comment by smellok** [comment]
这么早，好的，我再试一次，谢谢了

**Comment by Lunaleeguo** [comment]
哈哈哈，没办法，得去实验室，花屏了可以暂时再把显卡id改为0x12345678，看看还能不能进系统；实在不行可以在win下安装一个HFS+软件，把修改的AppleIntelSKLGraphicsFramebuffer.kext替换为原版

**Comment by smellok** [comment]
好的，谢谢了！
