### ISSUE TITLE
i5 hd520版本

### ISSUE THREAD

**Issue by vagrantk1d** [Lunaleeguo/Surface-Pro-4-Sierra#7]
界面显示system uptime in nanoseconds 然后直接重启，如图
![img_20171014_192956](https://user-images.githubusercontent.com/30520116/31725188-4cfff9ac-b456-11e7-8eaa-ee66e082e227.jpg)

**Comment by lyklll** [comment]
请问你解决了吗？

**Comment by vagrantk1d** [comment]
> 请问你解决了吗？

没有，我买了台mac
